# Generated by Django 3.2.4 on 2021-07-02 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0002_auto_20210628_1109'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensornode',
            name='motionDetected',
            field=models.IntegerField(default=0),
        ),
    ]
